# '---' is used to separate the definitions of the components/resources

#This YAML file defines a Deployment resource in Kubernetes. The Deployment is named 
#"mongodb-deployment" 
#and it is used to manage the deployment of a MongoDB database.

#The Deployment specifies that it should have one replica of the Pod running at all times, 
#using the replicas field. The selector field matchLabels specifies the label app: mongodb,
# which is used to select the Pods that the Deployment should manage.

#The template field defines the specification for the Pod that will be created by the Deployment. 
#The Pod contains a single container named "mongodb", which is based on the latest MongoDB image.
# The container listens on port 27017 and exposes the MongoDB database. The environment variables
# MONGO_INITDB_ROOT_USERNAME and MONGO_INITDB_ROOT_PASSWORD are set using values from a Kubernetes
#Secret named "secret", which provides secure storage for sensitive data. The values for these environment
#variables are read from the key-value pairs mongo-root-username and mongo-root-password in the Secret.

# Deployment for the mongodb server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
          - containerPort: 27017
        env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mongo-root-password 

---

# Deployment for mongo-express
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        ports:
          - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: secret
                key: mongo-root-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: mongo-root-password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongo-configmap
                key: database_url

---

# Deployment for flask-app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: thelastcube/flask-app:latest
        ports:
        - containerPort: 5001
        imagePullPolicy: Always
        env:
        - name: user
          valueFrom:
            secretKeyRef:
              name: secret
              key: mongo-root-username
        - name: password
          valueFrom:
            secretKeyRef:
              name: secret
              key: mongo-root-password 
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-configmap
              key: database_url