# Environment variables (username & password) required by the mongodb server

apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  mongo-root-username: cm9vdA==
  mongo-root-password: cm9vdA==